"use client";
import React from "react";
import { BackgroundGradient } from "./ui/background-gradient";
//import { IconAppWindow } from "@tabler/icons-react";
import Image from "next/image";
import Designer from "@/data/Designer.png"

export function About() {
  return (
    <div>
      <h1 className="heading mb-10"id="About">About <span className="text-red-300">Me</span></h1>
      <BackgroundGradient className="rounded-[22px] max-w-full p-4 sm:p-10 bg-white dark:bg-zinc-900  lg:flex flex-row">
        <Image
          src={Designer}
          alt="jordans"
          height="300"
          width="300"
          className="object-contain rounded-2xl"
        />
        <p className="text-sm text-neutral-600 dark:text-neutral-400 lg:m-7" >
          I’m an engineer fueled by a deep passion for solving real-world problems and crafting future-forward solutions. With a bold vision to revolutionize the hardware industry, I blend technical expertise, entrepreneurial mindset, and cutting-edge research in quantum technologies and photonics.

Driven by innovation, I stay ahead of the curve with constant learning and exploration of emerging technologies. My mission is to bridge the gap between science and society — transforming advanced concepts into impactful, real-world applications that shape a smarter, more sustainable future.

Whether it's building hardware that redefines what's possible or exploring the frontiers of physics and technology, I’m here to make things better — one breakthrough at a time.
<br />To be frank, I'm a very honest, humorous person. so I would like to say that all this information about myself generated by AI with a complete touch of my personality. I think you thought so right?</p>
      </BackgroundGradient>
    </div>
  );
}
